# name: docker image build and run test
name: docker image build test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:11-alpine
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_DB: rails_test
    #       POSTGRES_USER: rails
    #       POSTGRES_PASSWORD: password
    # env:
    #   RAILS_ENV: test
    #   DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 3.2.2

    # - name: Install dependencies
    #   run: |
    #     gem install bundler
    #     bundle install

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t action-test-app .
        echo ${{ github.sha }}}
